name: arc_env
channels:
  - defaults
  - rmg
  - conda-forge
dependencies:
  - conda-forge::ase=3.18.0
  - cairo=1.14.12
  - cairocffi=0.9.0
  - rmg::cantera=2.4.0
  - conda-forge::cclib>=1.6.0
  - rmg::chemprop
  - coolprop=6.2.1
  - coverage=5.4
  - cython=0.29.21
  - ffmpeg=4.2.2
  - rmg::gprof2dot=2017.9.19
  - graphviz=2.40.1
  - h5py=2.10.0
  - ipython=7.20.0
  - jinja2=2.11.3
  - jupyter=1.0.0
  - rmg::lpsolve55
  - markupsafe=1.1.1
  - matplotlib=3.3.2
  - rmg::mopac
  - mpmath=1.1.0
  - rmg::muq2
  - networkx=2.5
  - nose=1.3.7
  - rmg::numdifftools=0.9.39
  - numpy=1.15.4
  - openbabel=2.4.1
  - pandas=1.1.5
  - paramiko=2.7.2
  - psutil=5.8.0
  - py3dmol=0.8.0
  - rmg::pydas=1.0.2
  - pydot=1.4.1
  - rmg::pydqed=1.0.1
  - pymongo=3.11.2
  - pyparsing=2.4.7
  - rmg::pyrdl=1.1.2
  - python=3.7.7
  - pyyaml=5.4.1
  - qcelemental=0.17.0
  - rmg::quantities=0.12.3
  - rmg::rdkit=2020.03.3.0
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - seaborn=0.11.1
  - sphinx=3.4.3
  - rmg::symmetry=1.0.1
  - xlwt=1.3.0
